<?php

namespace _support;

use GuzzleHttp\Client;
use GuzzleHttp\Promise\PromiseInterface;

class MockGuzzleClient extends Client {
	private array $lastRequest = [];
	public function requestAsync( string $method, $uri = '', array $options = [] ): PromiseInterface {
		$this->lastRequest = $options;
		return parent::requestAsync( $method, $uri, $options ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return array
	 */
	public function getLastRequest(): array {
		return $this->lastRequest;
	}

}
