name: Run CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: 7.4
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer update --no-interaction --no-progress"

      - name: Run test cases
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          timeout_minutes: 5
          retry_on: error
          command: php vendor/bin/codecept run
        env:
          PORTAL_LOGIN_EMAIL: ${{ secrets.PORTAL_LOGIN_EMAIL }}
          PORTAL_LOGIN_PASSWORD: ${{ secrets.PORTAL_LOGIN_PASSWORD }}
